install.packages("devtools")
library("devtools")

install_version("assertthat", version = "0.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("AUC", version = "0.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("base64enc", version = "0.1-3", type = "source", upgrade_dependencies = FALSE)
install_version("BH", version = "1.69.0-1", type = "source", upgrade_dependencies = FALSE)
install_version("bindr", version = "0.1.1", type = "source", upgrade_dependencies = FALSE)
install_version("bindrcpp", version = "0.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("bit", version = "1.1-14", type = "source", upgrade_dependencies = FALSE)
install_version("bitops", version = "1.0-6", type = "source", upgrade_dependencies = FALSE)
install_version("cli", version = "1.1.0", type = "source", upgrade_dependencies = FALSE)
install_version("colorspace", version = "1.4-1", type = "source", upgrade_dependencies = FALSE)
install_version("crosstalk", version = "1.0.0", type = "source", upgrade_dependencies = FALSE)
install_version("curl", version = "3.3", type = "source", upgrade_dependencies = FALSE)
install_version("data.table", version = "1.12.0", type = "source", upgrade_dependencies = FALSE)
install_version("DBI", version = "1.0.0", type = "source", upgrade_dependencies = FALSE)
install_version("diagram", version = "1.6.4", type = "source", upgrade_dependencies = FALSE)
install_version("dichromat", version = "2.0-0", type = "source", upgrade_dependencies = FALSE)
install_version("digest", version = "0.6.18", type = "source", upgrade_dependencies = FALSE)
install_version("dplyr", version = "0.8.0.1", type = "source", upgrade_dependencies = FALSE)
install_version("DT", version = "0.5", type = "source", upgrade_dependencies = FALSE)
install_version("evaluate", version = "0.13", type = "source", upgrade_dependencies = FALSE)
install_version("fastmatch", version = "1.1-0", type = "source", upgrade_dependencies = FALSE)
install_version("ff", version = "2.2-14", type = "source", upgrade_dependencies = FALSE)
install_version("ffbase", version = "0.12.7", type = "source", upgrade_dependencies = FALSE)
install_version("formatR", version = "1.6", type = "source", upgrade_dependencies = FALSE)
install_version("futile.logger", version = "1.4.3", type = "source", upgrade_dependencies = FALSE)
install_version("futile.options", version = "1.0.1", type = "source", upgrade_dependencies = FALSE)
# gdtools was moved to archive and cannot be installed via install_version
install_github("davidgohel/gdtools") # 0.1.8
install_version("ggplot2", version = "3.1.0", type = "source", upgrade_dependencies = FALSE)
install_version("git2r", version = "0.24.0", type = "source", upgrade_dependencies = FALSE)
install_version("glue", version = "1.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("gridExtra", version = "2.3", type = "source", upgrade_dependencies = FALSE)
install_version("gtable", version = "0.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("hexbin", version = "1.27.2", type = "source", upgrade_dependencies = FALSE)
install_version("highr", version = "0.8", type = "source", upgrade_dependencies = FALSE)
install_version("hms", version = "0.4.2", type = "source", upgrade_dependencies = FALSE)
install_version("htmltools", version = "0.3.6", type = "source", upgrade_dependencies = FALSE)
install_version("htmlwidgets", version = "1.3", type = "source", upgrade_dependencies = FALSE)
install_version("httpuv", version = "1.4.5.1", type = "source", upgrade_dependencies = FALSE)
install_version("httr", version = "1.4.0", type = "source", upgrade_dependencies = FALSE)
install_version("jsonlite", version = "1.6", type = "source", upgrade_dependencies = FALSE)
install_version("knitr", version = "1.21", type = "source", upgrade_dependencies = FALSE)
install_version("labeling", version = "0.3", type = "source", upgrade_dependencies = FALSE)
install_version("lambda.r", version = "1.2.3", type = "source", upgrade_dependencies = FALSE)
install_version("lazyeval", version = "0.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("magrittr", version = "1.5", type = "source", upgrade_dependencies = FALSE)
install_version("mailR", version = "0.4.1", type = "source", upgrade_dependencies = FALSE)
install_version("markdown", version = "0.9", type = "source", upgrade_dependencies = FALSE)
install_version("mime", version = "0.6", type = "source", upgrade_dependencies = FALSE)
install_version("munsell", version = "0.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("officer", version = "0.3.3", type = "source", upgrade_dependencies = FALSE)
install_version("openssl", version = "1.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("openxlsx", version = "4.1.0", type = "source", upgrade_dependencies = FALSE)
install_version("pack", version = "0.1-1", type = "source", upgrade_dependencies = FALSE)
install_version("packrat", version = "0.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("pkgconfig", version = "2.0.2", type = "source", upgrade_dependencies = FALSE)
install_version("plogr", version = "0.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("plotly", version = "4.8.0", type = "source", upgrade_dependencies = FALSE)
install_version("plyr", version = "1.8.4", type = "source", upgrade_dependencies = FALSE)
install_version("png", version = "0.1-7", type = "source", upgrade_dependencies = FALSE)
install_version("purrr", version = "0.3.2", type = "source", upgrade_dependencies = FALSE)
install_version("PythonInR", version = "0.1-6", type = "source", upgrade_dependencies = FALSE)
install_version("R.methodsS3", version = "1.7.1", type = "source", upgrade_dependencies = FALSE)
install_version("R.oo", version = "1.21.0", type = "source", upgrade_dependencies = FALSE)
install_version("R.utils", version = "2.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("R6", version = "2.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("RColorBrewer", version = "1.1-2", type = "source", upgrade_dependencies = FALSE)
install_version("Rcpp", version = "1.0.1", type = "source", upgrade_dependencies = FALSE)
install_version("RcppEigen", version = "0.3.3.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("RcppParallel", version = "4.4.2", type = "source", upgrade_dependencies = FALSE)
install_version("RCurl", version = "1.95-4.12", type = "source", upgrade_dependencies = FALSE)
install_version("readr", version = "1.3.1", type = "source", upgrade_dependencies = FALSE)
# ReporteRsjars was moved to archive and cannot be installed via install_version.
# This library MUST be installed before "ReporteRs" library
install_github("davidgohel/ReporteRsjars") # 0.0.4
install_version("ReporteRs", version = "0.8.10", type = "source", upgrade_dependencies = FALSE)
install_version("reshape2", version = "1.4.3", type = "source", upgrade_dependencies = FALSE)
install_version("rJava", version = "0.9-11", type = "source", upgrade_dependencies = FALSE)
install_version("RJDBC", version = "0.2-7.1", type = "source", upgrade_dependencies = FALSE)
install_version("RJSONIO", version = "1.3-1.1", type = "source", upgrade_dependencies = FALSE)
install_version("rlang", version = "0.3.3", type = "source", upgrade_dependencies = FALSE)
install_version("rstudioapi", version = "0.9.0", type = "source", upgrade_dependencies = FALSE)
install_version("rvg", version = "0.1.9", type = "source", upgrade_dependencies = FALSE)
install_version("scales", version = "1.0.0", type = "source", upgrade_dependencies = FALSE)
install_version("shape", version = "1.4.4", type = "source", upgrade_dependencies = FALSE)
install_version("shiny", version = "1.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("shinycssloaders", version = "0.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("shinydashboard", version = "0.7.1", type = "source", upgrade_dependencies = FALSE)
install_version("snow", version = "0.4-3", type = "source", upgrade_dependencies = FALSE)
install_version("sourcetools", version = "0.1.7", type = "source", upgrade_dependencies = FALSE)
install_version("stringi", version = "1.3.1", type = "source", upgrade_dependencies = FALSE)
install_version("stringr", version = "1.4.0", type = "source", upgrade_dependencies = FALSE)
install_version("survAUC", version = "1.0-5", type = "source", upgrade_dependencies = FALSE)
install_version("tibble", version = "2.1.1", type = "source", upgrade_dependencies = FALSE)
install_version("tidyr", version = "0.8.2", type = "source", upgrade_dependencies = FALSE)
install_version("tidyselect", version = "0.2.5", type = "source", upgrade_dependencies = FALSE)
install_version("uuid", version = "0.1-2", type = "source", upgrade_dependencies = FALSE)
install_version("viridisLite", version = "0.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("whisker", version = "0.4", type = "source", upgrade_dependencies = FALSE)
install_version("withr", version = "2.1.2", type = "source", upgrade_dependencies = FALSE)
install_version("xgboost", version = "0.81.0.1", type = "source", upgrade_dependencies = FALSE)
install_version("XML", version = "3.98-1.17", type = "source", upgrade_dependencies = FALSE)
install_version("xml2", version = "1.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("xtable", version = "1.8-3", type = "source", upgrade_dependencies = FALSE)
install_version("yaml", version = "2.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("zip", version = "2.0.0", type = "source", upgrade_dependencies = FALSE)
install_version('maptools', version = "0.9-5", upgrade_dependencies = FALSE)
install_version('sp', version = "1.3-1", upgrade_dependencies = FALSE)
install_version('raster', version = "2.9-5", repos = c('https://cran.cnr.berkeley.edu/'), upgrade_dependencies = FALSE)
install_version('rgeos', version = "0.4-3", repos = c('https://cran.cnr.berkeley.edu/'), upgrade_dependencies = FALSE)
install_version('jqr', version = "1.1.0", repos = c('https://cran.cnr.berkeley.edu/'), upgrade_dependencies = FALSE)
install_version('geojson', version = "0.3.2", repos = c('https://cran.cnr.berkeley.edu/'), upgrade_dependencies = FALSE)
install_version('KernSmooth', version = "2.23-15", repos = c('https://cran.cnr.berkeley.edu/'), upgrade_dependencies = FALSE)
install_version("drat", version = "0.1.5", type = "source", upgrade_dependencies = FALSE)
remotes::install_github("miraisolutions/godmode", upgrade_dependencies = FALSE)
drat::addRepo(c("OHDSI", "cloudyr"))

# DO NOT CHANGE ORDER OF THE FOLLOWING INSTRUCTIONS
# Do not use install_github to install BigKnn library
install.packages("BigKnn")
install_github("OHDSI/CohortMethod", ref = "v3.0.2", upgrade_dependencies = FALSE)
install_github("OHDSI/DatabaseConnector", ref = "96a33f2", upgrade_dependencies = FALSE) #develop
install_github("OHDSI/DatabaseConnectorJars", ref = "v1.1.0", upgrade_dependencies = FALSE)
install_github("OHDSI/EmpiricalCalibration", ref = "v1.4.0", upgrade_dependencies = FALSE)
install_github("OHDSI/FeatureExtraction", ref = "v2.2.2", upgrade_dependencies = FALSE)
install_github("OHDSI/OhdsiRTools", ref = "v1.5.5", upgrade_dependencies = FALSE)
install_github("OHDSI/SqlRender", ref = "6c74347", upgrade_dependencies = FALSE)
install_github("OHDSI/Cyclops", ref = "v2.0.2", upgrade_dependencies = FALSE)
install_github("OHDSI/OhdsiSharing", ref = "v0.1.3", upgrade_dependencies = FALSE)
install_github("OHDSI/MethodEvaluation", ref = "98ae26e", upgrade_dependencies = FALSE)
install_github("OHDSI/PatientLevelPrediction", ref = "v3.0.1", upgrade_dependencies = FALSE)
install_bitbucket("Floooo/PythonInR", upgrade_dependencies = FALSE)
install_github("rstudio/keras", upgrade_dependencies = FALSE)

library(keras)
install_keras()
