library("devtools")
install_version("openxlsx", version = "4.1.0", type = "source", upgrade_dependencies = FALSE)
install_version("pack", version = "0.1-1", type = "source", upgrade_dependencies = FALSE)
install_version("packrat", version = "0.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("pkgconfig", version = "2.0.3", type = "source", upgrade_dependencies = FALSE)
install_version("plogr", version = "0.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("plotly", version = "4.9.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("plyr", version = "1.8.6", type = "source", upgrade_dependencies = FALSE)
install_version("png", version = "0.1-7", type = "source", upgrade_dependencies = FALSE)
install_version("purrr", version = "0.3.4", type = "source", upgrade_dependencies = FALSE)
install_version("PythonInR", version = "0.1-12", type = "source", upgrade_dependencies = FALSE)
install_version("R.methodsS3", version = "1.8.1", type = "source", upgrade_dependencies = FALSE)
install_version("R.oo", version = "1.24.0", type = "source", upgrade_dependencies = FALSE)
install_version("R.utils", version = "2.10.1", type = "source", upgrade_dependencies = FALSE)
install_version("R6", version = "2.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("RColorBrewer", version = "1.1-2", type = "source", upgrade_dependencies = FALSE)
install_version("Rcpp", version = "1.0.6", type = "source", upgrade_dependencies = FALSE)
install_version("RcppEigen", version = "0.3.3.9.1", type = "source", upgrade_dependencies = FALSE)
install_version("RcppParallel", version = "4.4.2", type = "source", upgrade_dependencies = FALSE)
install_version("RCurl", version = "1.98-1.2", type = "source", upgrade_dependencies = FALSE)
install_version("readr", version = "1.4.0", type = "source", upgrade_dependencies = FALSE)
# ReporteRsjars was moved to archive and cannot be installed via install_version.
# This library MUST be installed before "ReporteRs" library
install_github("davidgohel/ReporteRsjars", ref ="0adc2ca", upgrade_dependencies = FALSE) # 0.0.4
install_version("ReporteRs", version = "0.8.10", type = "source", upgrade_dependencies = FALSE)
install_version("reshape2", version = "1.4.4", type = "source", upgrade_dependencies = FALSE)
install_version("rJava", version = "1.0-4", type = "source", upgrade_dependencies = FALSE)