library("devtools")
drat::addRepo(c("OHDSI", "cloudyr"))
# DO NOT CHANGE ORDER OF THE FOLLOWING INSTRUCTIONS
install_github("OHDSI/Cyclops", ref = "v3.2.0", upgrade = "never")
install_github("OHDSI/ParallelLogger", ref = "v3.0.1", upgrade = "never")
install_github("OHDSI/BigKnn", ref = "v1.0.1", upgrade = "never")
install.packages("VennDiagram")
install_github("rstudio/reticulate", ref = "1.13", upgrade = "never") # 1.13 per https://github.com/rstudio/keras/issues/869
install_github("OHDSI/CohortMethod", ref = "v4.2.3", upgrade = "never")
install_github("OHDSI/DatabaseConnector", ref = "v5.1.0", upgrade = "never")
install_github("OHDSI/EmpiricalCalibration", ref = "v3.1.1", upgrade = "never")
install_github("OHDSI/Andromeda", ref = "v0.6.1", upgrade = "never")
install_github("OHDSI/FeatureExtraction", ref = "v3.2.0", upgrade = "never")
install_github("OHDSI/OhdsiRTools", ref = "v2.0.2", upgrade = "never")
install_github("OHDSI/SqlRender", ref = "v1.10.0", upgrade = "never")
install_github("OHDSI/OhdsiSharing", ref = "v0.2.2", upgrade = "never")
install_github("OHDSI/ROhdsiWebApi", ref = "v1.3.1", upgrade = "never")
install_github("OHDSI/CohortDiagnostics", ref = "v3.0.3", upgrade = "never")
install_github("OHDSI/MethodEvaluation", ref = "v2.2.0", upgrade = "never")
install_github("OHDSI/PatientLevelPrediction", ref = "v6.0.0", upgrade = "never")
install_github("OHDSI/CohortGenerator", ref = "v0.6.0", upgrade = "never")

library(PatientLevelPrediction)
configurePython(envname='PLP', envtype='conda')

install_github("rstudio/keras", ref = "v2.4.0", upgrade = "never")
