library("devtools")
install_github('thomasp85/systemfonts', ref = "37ed27b", upgrade = "never")
install_github("davidgohel/gdtools", ref = "8a94fa3", upgrade = "never")
install_version("ggplot2", version = "3.1.0", type = "source", upgrade_dependencies = FALSE)
install_version("git2r", version = "0.24.0", type = "source", upgrade_dependencies = FALSE)
install_version("glue", version = "1.4.1", type = "source", upgrade_dependencies = FALSE)
install_version("gridExtra", version = "2.3", type = "source", upgrade_dependencies = FALSE)
install_version("gtable", version = "0.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("hexbin", version = "1.27.2", type = "source", upgrade_dependencies = FALSE)
install_version("highr", version = "0.8", type = "source", upgrade_dependencies = FALSE)
install_version("hms", version = "0.4.2", type = "source", upgrade_dependencies = FALSE)
install_version("htmltools", version = "0.3.6", type = "source", upgrade_dependencies = FALSE)
install_version("htmlwidgets", version = "1.3", type = "source", upgrade_dependencies = FALSE)
install_version("httpuv", version = "1.4.5.1", type = "source", upgrade_dependencies = FALSE)
install_version("httr", version = "1.4.0", type = "source", upgrade_dependencies = FALSE)
install_version("jsonlite", version = "1.6", type = "source", upgrade_dependencies = FALSE)
install_version("knitr", version = "1.21", type = "source", upgrade_dependencies = FALSE)
install_version("labeling", version = "0.3", type = "source", upgrade_dependencies = FALSE)
install_version("lambda.r", version = "1.2.3", type = "source", upgrade_dependencies = FALSE)
install_version("lazyeval", version = "0.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("magrittr", version = "1.5", type = "source", upgrade_dependencies = FALSE)
install_version("mailR", version = "0.4.1", type = "source", upgrade_dependencies = FALSE)
install_version("markdown", version = "0.9", type = "source", upgrade_dependencies = FALSE)
install_version("mime", version = "0.6", type = "source", upgrade_dependencies = FALSE)
install_version("munsell", version = "0.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("officer", version = "0.3.10", type = "source", upgrade_dependencies = FALSE)
install_version("openssl", version = "1.2.1", type = "source", upgrade_dependencies = FALSE)