library("devtools")
install_github("rstudio/tensorflow", ref = "v2.5.0", upgrade = "never")
install_version("yaml", version = "2.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("zip", version = "2.1.1", type = "source", upgrade_dependencies = FALSE)
install_version('maptools', version = "1.0-2", upgrade_dependencies = FALSE)
install_version('sp', version = "1.4-5", upgrade_dependencies = FALSE)
install_version('raster', version = "3.4-5", upgrade_dependencies = FALSE)
install_version('rgeos', version = "0.5-5", upgrade_dependencies = FALSE)
install_version('jqr', version = "1.2.0", upgrade_dependencies = FALSE)
install_version('geojson', version = "0.3.4", upgrade_dependencies = FALSE)
install_version('KernSmooth', version = "2.23-18", upgrade_dependencies = FALSE)
install_version("drat", version = "0.1.8", type = "source", upgrade_dependencies = FALSE)
install_github("miraisolutions/godmode", upgrade_dependencies = FALSE)
