library("devtools")
install_version("tensorflow", version = "2.9.0", type = "source", upgrade_dependencies = FALSE)
install_version("yaml", version = "2.3.5", type = "source", upgrade_dependencies = FALSE)
install_version("zip", version = "2.2.1", type = "source", upgrade_dependencies = FALSE)
install_version('maptools', version = "1.1-4", upgrade_dependencies = FALSE)
install_version('sp', version = "1.5-0", upgrade_dependencies = FALSE)
install_version('raster', version = "3.6-3", upgrade_dependencies = FALSE)
install_version('rgeos', version = "0.5-9", upgrade_dependencies = FALSE)
install_version('jqr', version = "1.2.3", upgrade_dependencies = FALSE)
install_version('geojson', version = "0.3.4", upgrade_dependencies = FALSE)
install_version('KernSmooth', version = "2.23-20", upgrade_dependencies = FALSE)
install_version("drat", version = "0.2.3", type = "source", upgrade_dependencies = FALSE)
install_github("miraisolutions/godmode", upgrade_dependencies = FALSE)
