install.packages("devtools")
library("devtools")

install_version("assertthat", version = "0.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("AUC", version = "0.3.0", type = "source", upgrade_dependencies = FALSE)
install_version("base64enc", version = "0.1-3", type = "source", upgrade_dependencies = FALSE)
install_version("BH", version = "1.72.0-3", type = "source", upgrade_dependencies = FALSE)
install_version("bindr", version = "0.1.1", type = "source", upgrade_dependencies = FALSE)
install_version("bindrcpp", version = "0.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("bit", version = "1.1-14", type = "source", upgrade_dependencies = FALSE)
install_version("bitops", version = "1.0-6", type = "source", upgrade_dependencies = FALSE)
install_version("cli", version = "2.5.0", type = "source", upgrade_dependencies = FALSE)
install_version("colorspace", version = "2.0-1", type = "source", upgrade_dependencies = FALSE)
install_version("crosstalk", version = "1.1.0.1", type = "source", upgrade_dependencies = FALSE)
install_version("curl", version = "4.3", type = "source", upgrade_dependencies = FALSE)
install_version("data.table", version = "1.13.6", type = "source", upgrade_dependencies = FALSE)
install_version("DBI", version = "1.1.1", type = "source", upgrade_dependencies = FALSE)
install_version("diagram", version = "1.6.4", type = "source", upgrade_dependencies = FALSE)
install_version("dichromat", version = "2.0-0", type = "source", upgrade_dependencies = FALSE)
install_version("dplyr", version = "1.0.5", type = "source", upgrade_dependencies = FALSE)
install_version("DT", version = "0.5", type = "source", upgrade_dependencies = FALSE)
install_version("ellipsis", version = "0.3.2", type = "source", upgrade_dependencies = FALSE)
install_version("evaluate", version = "0.14", type = "source", upgrade_dependencies = FALSE)
install_version("fastmatch", version = "1.1-0", type = "source", upgrade_dependencies = FALSE)
install_version("formatR", version = "1.7", type = "source", upgrade_dependencies = FALSE)
install_version("futile.logger", version = "1.4.3", type = "source", upgrade_dependencies = FALSE)
install_version("futile.options", version = "1.0.1", type = "source", upgrade_dependencies = FALSE)
