install.packages("devtools")
library("devtools")

install_version("testthat", version = "3.1.4", type = "source", upgrade_dependencies = FALSE)
install_version("rematch2", version = "2.1.2", type = "source", upgrade_dependencies = FALSE)

install_version("assertthat", version = "0.2.1", type = "source", upgrade_dependencies = FALSE)
install_version("AUC", version = "0.3.2", type = "source", upgrade_dependencies = FALSE)
install_version("base64enc", version = "0.1-3", type = "source", upgrade_dependencies = FALSE)
install_version("BH", version = "1.78.0-0", type = "source", upgrade_dependencies = FALSE)
install_version("bindr", version = "0.1.1", type = "source", upgrade_dependencies = FALSE)
install_version("bindrcpp", version = "0.2.2", type = "source", upgrade_dependencies = FALSE)
install_version("bit", version = "4.0.4", type = "source", upgrade_dependencies = FALSE)
install_version("bitops", version = "1.0-7", type = "source", upgrade_dependencies = FALSE)
install_version("cli", version = "3.4.1", type = "source", upgrade_dependencies = FALSE)
install_version("colorspace", version = "2.0-3", type = "source", upgrade_dependencies = FALSE)
install_version("crosstalk", version = "1.2.0", type = "source", upgrade_dependencies = FALSE)
install_version("curl", version = "4.3.2", type = "source", upgrade_dependencies = FALSE)
install_version("data.table", version = "1.14.2", type = "source", upgrade_dependencies = FALSE)
install_version("DBI", version = "1.1.3", type = "source", upgrade_dependencies = FALSE)
install_version("diagram", version = "1.6.5", type = "source", upgrade_dependencies = FALSE)
install_version("dichromat", version = "2.0-0.1", type = "source", upgrade_dependencies = FALSE)
install_version("dplyr", version = "1.0.10", type = "source", upgrade_dependencies = FALSE)
install_version("DT", version = "0.25", type = "source", upgrade_dependencies = FALSE)
install_version("evaluate", version = "0.16", type = "source", upgrade_dependencies = FALSE)
install_version("fastmatch", version = "1.1-3", type = "source", upgrade_dependencies = FALSE)
install_version("formatR", version = "1.12", type = "source", upgrade_dependencies = FALSE)
install_version("futile.logger", version = "1.4.3", type = "source", upgrade_dependencies = FALSE)
install_version("futile.options", version = "1.0.1", type = "source", upgrade_dependencies = FALSE)
